data_dir: data_dir
save_dir: save_dir

data_split:
  val_size: 0
  test_size: 1500

coder:
  entry_coder_type: file_name
  cased: True
  trim_len: 0
  rem_equals: False

model: cnn

optimizer:
  lr: 0.001
  weight_decay: 0.001

batch_size: 32

train:
  epochs: 25