data_dir: data_dir
features_dir: features_dir
save_dir: save_dir

data_split:
  val_size: 0
  test_size: 450

coder:
  entry_coder_type: file_name
  cased: True
  trim_len: 0
  rem_equals: False

model:
  emb_type: cnn

optimizer:
  lr: 0.001
  weight_decay: 0.001

train:
  epochs: 10
  update_every: 4